server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce:
        pool:
          max-active: 10   # 最大连接数
          max-idle: 10  # 最大空闲连接数
          min-idle: 1  # 最小空闲连接数
          time-between-eviction-runs: 10s  # 每隔多久检查一次连接池中的连接状态。
  jackson:
    default-property-inclusion: non_null   # json自动忽略null值，不需要序列化

mybatis-plus:
  type-aliases-package: com.syr.entity    # 扫描包
logging:
  level:
    com.syr: debug
